% ============================================================
% ONE_compute_graph_theory_metrics.m
%
% PURPOSE: Compute weighted graph theory metrics across 400 proportional
%          density thresholds (0.25% to 100% in 0.25% increments) for each
%          subject, plus normalized versions of GE, ACC, path
%          length, and small-world.
%
%          Per subject, per threshold:
%            Observed: weighted GE, weighted ACC, mean nodal strength
%            Normalized: GE_obs / mean(null GE),
%                        ACC_obs / mean(null ACC),
%                        L_obs / mean(null L),
%                        SW = (ACC_obs/mean(null ACC)) /
%                             (L_obs/mean(null L))
%          Also: network density on unthresholded matrix (den_100.00).
%
%          Null models: 100 per subject per threshold, generated by
%          null_model_und_sign() with bin_swaps=10 (binary topology
%          phase) and wei_freq=1 (resort weights at every step), per
%          Methods 2.6.
%
% INPUTS:  For each subject in IN_DIR (subject-subfolder layout):
%            - IN_DIR/<subject>/<subject>_mu_weighted.csv
%              (output of ONE_apply_mu_norm.m in 01_connectome_construction/)
%
% OUTPUTS: Single Excel table at OUT_FILE with columns:
%            - ID                              (sub-###)
%            - den_100.00                      (network density)
%            - GE_<dens>                       (raw weighted GE, 400 cols)
%            - ACC_<dens>                      (raw weighted ACC, 400 cols)
%            - str_<dens>                      (raw mean strength, 400 cols)
%            - rand_norm_wei_GE_<dens>         (normalized GE, 400 cols)
%            - rand_norm_wei_ACC_<dens>        (normalized ACC, 400 cols)
%            - rand_norm_wei_L_<dens>          (normalized path length, 400 cols)
%            - rand_norm_wei_SW_<dens>         (normalized small-world, 400 cols)
%          Note: Group column is NOT written here. Group membership is
%          merged in downstream via TWO_merge_clinical_and_metrics.R.
%
% REQUIRES: MATLAB R2025b (or similar), Brain Connectivity Toolbox.
%           BCT functions used: threshold_proportional, null_model_und_sign,
%           clustering_coef_wu, efficiency_wei, charpath, distance_wei,
%           weight_conversion, strengths_und, density_und.
%
% RUNTIME: Long. Expect several days, especially if run on a 
%          local machine.
% ============================================================

clear; clc;

% ============================================================
% CONFIG -- edit before running
% ============================================================
% Paths are relative to the repository root; run MATLAB from the repo root
% (or set an absolute path here if launching from elsewhere).
IN_DIR   = 'data/connectomes/mu_weighted';  % parent dir with per-subject subfolders
OUT_FILE = 'data/intermediate/graph_theory_metrics_per_subject.xlsx';
SUBLIST  = '';     % optional: path to text file with subject IDs (one per line). Leave '' to process all sub-* in IN_DIR.
FORCE    = false;  % set true to overwrite existing OUT_FILE

% --- Density thresholds ---
DENSITY_START = 0.0025;
DENSITY_STEP  = 0.0025;
DENSITY_END   = 1.0;

% --- Null model settings ---
N_RAND        = 100;   % null networks per subject per threshold
WEI_BIN_SWAPS = 10;    % binary-phase swaps per edge in null_model_und_sign
WEI_FREQ      = 1;     % weight-sorting frequency (1 = every step)

% --- Charpath settings ---
CHARPATH_DIAG = 0;     % 0 = exclude diagonal
CHARPATH_INF  = 0;     % 0 = exclude infinite distances (disconnected pairs)

% --- Parallelization ---
USE_PARALLEL = true;

% --- Expected matrix size (sanity check) ---
EXPECTED_N_NODES = 84;

% ============================================================
% Logic below -- do not edit
% ============================================================

% Idempotency
if exist(OUT_FILE, 'file') && ~FORCE
    fprintf('Output already exists: %s\n', OUT_FILE);
    fprintf('Set FORCE=true to overwrite. Exiting.\n');
    return;
end

% Ensure output directory exists
[out_dir, ~, ~] = fileparts(OUT_FILE);
if ~isfolder(out_dir), mkdir(out_dir); end

% Density grid
densities = DENSITY_START : DENSITY_STEP : DENSITY_END;
n_thresh = numel(densities);

% Header banner
fprintf('\n=========================================================\n');
fprintf('  GRAPH THEORY METRIC COMPUTATION\n');
fprintf('=========================================================\n');
fprintf('  Input dir:    %s\n', IN_DIR);
fprintf('  Output file:  %s\n', OUT_FILE);
fprintf('  Densities:    %d thresholds (%.4f : %.4f : %.4f)\n', ...
    n_thresh, DENSITY_START, DENSITY_STEP, DENSITY_END);
fprintf('  Null models:  %d per threshold per subject\n', N_RAND);
fprintf('  Null params:  bin_swaps=%d, wei_freq=%.2f\n', WEI_BIN_SWAPS, WEI_FREQ);
fprintf('=========================================================\n\n');

% Launch parallel pool
if USE_PARALLEL && isempty(gcp('nocreate'))
    parpool('local', feature('numcores'));
end
if USE_PARALLEL
    fprintf('Parallel pool: %d workers\n\n', gcp().NumWorkers);
end

% Resolve subject list
if ~isempty(SUBLIST) && exist(SUBLIST, 'file')
    fid = fopen(SUBLIST); subjects = textscan(fid, '%s'); fclose(fid);
    subjects = subjects{1};
else
    d = dir(fullfile(IN_DIR, 'sub-*'));
    subjects = {d([d.isdir]).name}';
end
n_sub = numel(subjects);
fprintf('Subjects found: %d\n\n', n_sub);

if n_sub == 0
    error('No subjects found in %s. Check IN_DIR.', IN_DIR);
end

% Density column labels: zero-padded 5-char strings (e.g., "00.25", "25.00", "100.00")
density_labels = cell(1, n_thresh);
for t = 1:n_thresh
    pct = densities(t) * 100;
    if pct >= 100
        density_labels{t} = '100.00';
    else
        density_labels{t} = sprintf('%05.2f', pct);
    end
end

% Preallocate result matrices
raw_wei_GE_all  = NaN(n_sub, n_thresh);
raw_wei_ACC_all = NaN(n_sub, n_thresh);
raw_wei_str_all = NaN(n_sub, n_thresh);
wei_GE_all      = NaN(n_sub, n_thresh);
wei_ACC_all     = NaN(n_sub, n_thresh);
wei_L_all       = NaN(n_sub, n_thresh);
wei_SW_all      = NaN(n_sub, n_thresh);
den_100_all     = NaN(n_sub, 1);
valid_mask      = true(n_sub, 1);

% Main processing loop
overall_tic = tic;
n_processed = 0;

for s = 1:n_sub
    subj_tic = tic;
    sub = subjects{s};
    in_csv = fullfile(IN_DIR, sub, [sub '_mu_weighted.csv']);

    fprintf('[%03d/%03d] %s ...', s, n_sub, sub);

    if ~exist(in_csv, 'file')
        fprintf(' SKIPPED (missing %s)\n', [sub '_mu_weighted.csv']);
        valid_mask(s) = false;
        continue;
    end

    W_raw = readmatrix(in_csv);
    if ~isequal(size(W_raw), [EXPECTED_N_NODES, EXPECTED_N_NODES])
        fprintf(' SKIPPED (dimensions %dx%d, expected %dx%d)\n', ...
            size(W_raw,1), size(W_raw,2), EXPECTED_N_NODES, EXPECTED_N_NODES);
        valid_mask(s) = false;
        continue;
    end

    % Symmetrize, zero diagonal, clip negatives
    W_raw = (W_raw + W_raw.') / 2;
    n = size(W_raw, 1);
    W_raw(1:n+1:end) = 0;
    W_raw(W_raw < 0) = 0;

    % Density at 100% (unthresholded)
    den_100_all(s) = density_und(W_raw);

    % Preallocate per-subject vectors
    raw_wei_GE  = NaN(1, n_thresh);
    raw_wei_ACC = NaN(1, n_thresh);
    raw_wei_str = NaN(1, n_thresh);
    wei_GE      = NaN(1, n_thresh);
    wei_ACC     = NaN(1, n_thresh);
    wei_L       = NaN(1, n_thresh);
    wei_SW      = NaN(1, n_thresh);

    % Threshold loop
    for t = 1:n_thresh
        p = densities(t);

        if mod(t, 10) == 1 || t == n_thresh
            fprintf('    Threshold %3d/%d (density=%.4f) ...', t, n_thresh, p);
            thresh_tic = tic;
        end

        W_thr = threshold_proportional(W_raw, p);
        if ~any(W_thr(:))
            continue;
        end

        % Observed weighted metrics
        obs_wei_GE  = efficiency_wei(W_thr);
        Ci_wei      = clustering_coef_wu(W_thr);
        obs_wei_ACC = mean(Ci_wei(~isinf(Ci_wei) & ~isnan(Ci_wei)));
        L_mat_wei   = weight_conversion(W_thr, 'lengths');
        D_wei       = distance_wei(L_mat_wei);
        obs_wei_L   = charpath(D_wei, CHARPATH_DIAG, CHARPATH_INF);
        obs_wei_str = mean(strengths_und(W_thr));

        raw_wei_GE(t)  = obs_wei_GE;
        raw_wei_ACC(t) = obs_wei_ACC;
        raw_wei_str(t) = obs_wei_str;

        % Null distributions
        null_wei_GE  = NaN(N_RAND, 1);
        null_wei_ACC = NaN(N_RAND, 1);
        null_wei_L   = NaN(N_RAND, 1);

        % Broadcast parameters into parfor scope
        p_bin = WEI_BIN_SWAPS;
        p_frq = WEI_FREQ;
        p_cd  = CHARPATH_DIAG;
        p_ci  = CHARPATH_INF;
        W_loc = W_thr;

        if USE_PARALLEL
            parfor r = 1:N_RAND
                W_null = null_model_und_sign(W_loc, p_bin, p_frq);
                null_wei_GE(r) = efficiency_wei(W_null);
                Ci_null = clustering_coef_wu(W_null);
                null_wei_ACC(r) = mean(Ci_null(~isinf(Ci_null) & ~isnan(Ci_null)));
                L_null = weight_conversion(W_null, 'lengths');
                D_null = distance_wei(L_null);
                null_wei_L(r) = charpath(D_null, p_cd, p_ci);
            end
        else
            for r = 1:N_RAND
                W_null = null_model_und_sign(W_loc, p_bin, p_frq);
                null_wei_GE(r) = efficiency_wei(W_null);
                Ci_null = clustering_coef_wu(W_null);
                null_wei_ACC(r) = mean(Ci_null(~isinf(Ci_null) & ~isnan(Ci_null)));
                L_null = weight_conversion(W_null, 'lengths');
                D_null = distance_wei(L_null);
                null_wei_L(r) = charpath(D_null, p_cd, p_ci);
            end
        end

        % Normalize
        mu_GE  = mean(null_wei_GE,  'omitnan');
        mu_ACC = mean(null_wei_ACC, 'omitnan');
        mu_L   = mean(null_wei_L,   'omitnan');
        if mu_GE  ~= 0, wei_GE(t)  = obs_wei_GE  / mu_GE;  end
        if mu_ACC ~= 0, wei_ACC(t) = obs_wei_ACC / mu_ACC; end
        if mu_L   ~= 0, wei_L(t)   = obs_wei_L   / mu_L;   end
        if mu_ACC ~= 0 && mu_L ~= 0
            gamma  = obs_wei_ACC / mu_ACC;
            lambda = obs_wei_L   / mu_L;
            if lambda ~= 0
                wei_SW(t) = gamma / lambda;
            end
        end

        if mod(t, 10) == 1 || t == n_thresh
            fprintf(' done (%.1f sec)\n', toc(thresh_tic));
        end
    end

    % Store
    raw_wei_GE_all(s, :)  = raw_wei_GE;
    raw_wei_ACC_all(s, :) = raw_wei_ACC;
    raw_wei_str_all(s, :) = raw_wei_str;
    wei_GE_all(s, :)      = wei_GE;
    wei_ACC_all(s, :)     = wei_ACC;
    wei_L_all(s, :)       = wei_L;
    wei_SW_all(s, :)      = wei_SW;

    n_processed = n_processed + 1;
    elapsed = toc(overall_tic);
    avg_per = elapsed / n_processed;
    est_rem = avg_per * (n_sub - s);
    fprintf(' done (%.1f min) | Elapsed: %.1f min | Est remaining: %.1f min\n', ...
        toc(subj_tic)/60, elapsed/60, est_rem/60);
end

% Trim invalid subjects
subjects = subjects(valid_mask);
raw_wei_GE_all  = raw_wei_GE_all(valid_mask, :);
raw_wei_ACC_all = raw_wei_ACC_all(valid_mask, :);
raw_wei_str_all = raw_wei_str_all(valid_mask, :);
wei_GE_all      = wei_GE_all(valid_mask, :);
wei_ACC_all     = wei_ACC_all(valid_mask, :);
wei_L_all       = wei_L_all(valid_mask, :);
wei_SW_all      = wei_SW_all(valid_mask, :);
den_100_all     = den_100_all(valid_mask);

% Build output table
fprintf('\nBuilding output table...\n');
T = table(subjects, 'VariableNames', {'ID'});
T.('den_100.00') = den_100_all;

for t = 1:n_thresh
    dlabel = density_labels{t};
    T.(sprintf('GE_%s',  dlabel)) = raw_wei_GE_all(:, t);
    T.(sprintf('ACC_%s', dlabel)) = raw_wei_ACC_all(:, t);
    % strength uses non-zero-padded format to match upstream convention
    pct = densities(t) * 100;
    if pct >= 100
        str_dlabel = '100.00';
    else
        str_dlabel = sprintf('%.2f', pct);
    end
    T.(sprintf('str_%s', str_dlabel)) = raw_wei_str_all(:, t);
    T.(sprintf('rand_norm_wei_GE_%s',  dlabel)) = wei_GE_all(:, t);
    T.(sprintf('rand_norm_wei_ACC_%s', dlabel)) = wei_ACC_all(:, t);
    T.(sprintf('rand_norm_wei_L_%s',   dlabel)) = wei_L_all(:, t);
    T.(sprintf('rand_norm_wei_SW_%s',  dlabel)) = wei_SW_all(:, t);
end

fprintf('Writing: %s\n', OUT_FILE);
writetable(T, OUT_FILE);

fprintf('\n=========================================================\n');
fprintf('  COMPLETE\n');
fprintf('=========================================================\n');
fprintf('  Processed: %d / %d subjects\n', numel(subjects), n_sub);
fprintf('  Columns:   %d (ID + den_100.00 + %d metrics)\n', width(T), width(T) - 2);
fprintf('  Time:      %.1f min (%.2f hours)\n', toc(overall_tic)/60, toc(overall_tic)/3600);
fprintf('  Output:    %s\n', OUT_FILE);
fprintf('=========================================================\n');